
modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Apache-2.0 License"
issueTrackerURL="https://github.com/lfaoanl/MarketCrates/issues" #optional

[[mods]] #mandatory
modId="marketcrates" #mandatory
version="1.4" #mandatory
displayName="Market Crates" #mandatory

updateJSONURL="http://lfaoanl.space/mc/marketcrates/update.json" #optional
displayURL="https://github.com/lfaoanl/MarketCrates/" #optional
logoFile="marketcrates_logo.png" #optional
# A text field displayed in the mod UI
authors="Lfaoanl" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Some crates to spice up your towns, markets, fishing docs, you name it!
- Available in all different wood types
- Shows their inventory contents
- You can stack them
- You can put a stick under it to give the crate in incline
Shift click the crate to place stack crates in the same block space.
Hit the crate with a stick to incline the crate. Hit it once with an axe to retrieve the stick (For creative mode right clicking with a stick toggles it)
'''
[[dependencies.marketcrates]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[38,)" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.marketcrates]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18,)"
   ordering="NONE"
   side="BOTH"